package BYUI.CIT260.RectangleOfFortune.frames;

import BYUI.CIT260.RectangleOfFortune.Enums.GameMenuItems;
import BYUI.CIT260.RectangleOfFortune.Enums.GuessType;
import BYUI.CIT260.RectangleOfFortune.exceptions.RectangleOfFortuneException;
import BYUI.CIT260.RectangleOfFortune.menu.controls.GameMenuControl;
import BYUI.CIT260.RectangleOfFortune.models.Game;
import BYUI.CIT260.RectangleOfFortune.models.Letter;
import BYUI.CIT260.RectangleOfFortune.models.Tile;
import BYUI.CIT260.RectangleOfFortune.views.GuessAConsonant;
import BYUI.CIT260.RectangleOfFortune.views.GuessAVowel;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Crossley Family
 */
public class GameFrame extends javax.swing.JFrame {
    Game game=null;
    GameMenuControl gameMenuControl=null;
    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    public GameFrame(Game game){
       this.game = game;
       this.gameMenuControl=new GameMenuControl(game);
       initComponents();
    }
    
    public void initializeForm() throws RectangleOfFortuneException{
        setGuessControlVisibility(false);
//        setGuessVowelControlVisibility(false);
        this.jlPlayerTurn.setText(game.getCurrentPlayerName() + GameMenuItems.PLAYERTURN.getText());
//        this.jTPuzzle.setText(game.displayPuzzle());
        showBackground();
        displayTranslate(game.getPuzzle().getCurrentPuzzle());
        this.jPlayerRankText.setText(this.gameMenuControl.showCurrentPlayerStanding(game.getPlayerList()));
//        this.jTMessages.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTGuess = new javax.swing.JTextArea();
        jbGuess = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbSpin = new javax.swing.JButton();
        jbBuyVowel = new javax.swing.JButton();
        jbSolvePuzzle = new javax.swing.JButton();
        jbQuitGame = new javax.swing.JButton();
        jpPlayerTurnIndicator = new javax.swing.JPanel();
        jlPlayerTurn = new javax.swing.JLabel();
        jlPlayerRank = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPlayerRankText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTWinValue = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTMessages = new javax.swing.JTextArea();
        jlSpinValue = new javax.swing.JLabel();
        jlPlayerTurnDisplay = new javax.swing.JLabel();
        jpPuzzle = new javax.swing.JPanel();
        jpPuzzleRow1 = new javax.swing.JPanel();
        jText12 = new javax.swing.JTextField();
        jText11 = new javax.swing.JTextField();
        jText10 = new javax.swing.JTextField();
        jText9 = new javax.swing.JTextField();
        jText8 = new javax.swing.JTextField();
        jText7 = new javax.swing.JTextField();
        jText6 = new javax.swing.JTextField();
        jText5 = new javax.swing.JTextField();
        jText4 = new javax.swing.JTextField();
        jText3 = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jText1 = new javax.swing.JTextField();
        jpPuzzleRow2 = new javax.swing.JPanel();
        jText25 = new javax.swing.JTextField();
        jText24 = new javax.swing.JTextField();
        jText23 = new javax.swing.JTextField();
        jText22 = new javax.swing.JTextField();
        jText21 = new javax.swing.JTextField();
        jText20 = new javax.swing.JTextField();
        jText19 = new javax.swing.JTextField();
        jText18 = new javax.swing.JTextField();
        jText17 = new javax.swing.JTextField();
        jText16 = new javax.swing.JTextField();
        jText15 = new javax.swing.JTextField();
        jText14 = new javax.swing.JTextField();
        jText13 = new javax.swing.JTextField();
        jText26 = new javax.swing.JTextField();
        jpPuzzleRow3 = new javax.swing.JPanel();
        jText39 = new javax.swing.JTextField();
        jText38 = new javax.swing.JTextField();
        jText37 = new javax.swing.JTextField();
        jText36 = new javax.swing.JTextField();
        jText35 = new javax.swing.JTextField();
        jText34 = new javax.swing.JTextField();
        jText33 = new javax.swing.JTextField();
        jText32 = new javax.swing.JTextField();
        jText31 = new javax.swing.JTextField();
        jText30 = new javax.swing.JTextField();
        jText29 = new javax.swing.JTextField();
        jText28 = new javax.swing.JTextField();
        jText27 = new javax.swing.JTextField();
        jText40 = new javax.swing.JTextField();
        jpPuzzleRow4 = new javax.swing.JPanel();
        jText52 = new javax.swing.JTextField();
        jText51 = new javax.swing.JTextField();
        jText50 = new javax.swing.JTextField();
        jText49 = new javax.swing.JTextField();
        jText48 = new javax.swing.JTextField();
        jText47 = new javax.swing.JTextField();
        jText46 = new javax.swing.JTextField();
        jText45 = new javax.swing.JTextField();
        jText44 = new javax.swing.JTextField();
        jText43 = new javax.swing.JTextField();
        jText42 = new javax.swing.JTextField();
        jText41 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rectangle Of Fortune!");

        jpBody.setBackground(new java.awt.Color(102, 153, 255));

        jTGuess.setColumns(20);
        jTGuess.setRows(1);
        jScrollPane1.setViewportView(jTGuess);

        jbGuess.setText("Make Guess");
        jbGuess.setToolTipText("");
        jbGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuessActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbSpin.setText("Spin");
        jbSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSpinActionPerformed(evt);
            }
        });

        jbBuyVowel.setText("Buy Vowel");
        jbBuyVowel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuyVowelActionPerformed(evt);
            }
        });

        jbSolvePuzzle.setText("Solve Puzzle");
        jbSolvePuzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSolvePuzzleActionPerformed(evt);
            }
        });

        jbQuitGame.setText("Quit Game");
        jbQuitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbQuitGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBuyVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSolvePuzzle, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSpin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuyVowel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSolvePuzzle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbQuitGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbBuyVowel, jbSolvePuzzle});

        jpPlayerTurnIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlPlayerTurn.setBackground(new java.awt.Color(153, 153, 255));
        jlPlayerTurn.setText("Player Turn Indicator");
        jlPlayerTurn.setToolTipText("");

        javax.swing.GroupLayout jpPlayerTurnIndicatorLayout = new javax.swing.GroupLayout(jpPlayerTurnIndicator);
        jpPlayerTurnIndicator.setLayout(jpPlayerTurnIndicatorLayout);
        jpPlayerTurnIndicatorLayout.setHorizontalGroup(
            jpPlayerTurnIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayerTurnIndicatorLayout.createSequentialGroup()
                .addComponent(jlPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jpPlayerTurnIndicatorLayout.setVerticalGroup(
            jpPlayerTurnIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayerTurnIndicatorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlPlayerRank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlPlayerRank.setText("Player Rank");

        jPlayerRankText.setEditable(false);
        jPlayerRankText.setColumns(20);
        jPlayerRankText.setRows(3);
        jScrollPane2.setViewportView(jPlayerRankText);

        jTWinValue.setEditable(false);
        jTWinValue.setBackground(new java.awt.Color(153, 204, 255));
        jTWinValue.setColumns(20);
        jTWinValue.setRows(1);
        jTWinValue.setToolTipText("");
        jScrollPane3.setViewportView(jTWinValue);

        jTMessages.setColumns(20);
        jTMessages.setRows(5);
        jScrollPane6.setViewportView(jTMessages);

        jlSpinValue.setText("Spin Value");

        jlPlayerTurnDisplay.setText("Player Turn");

        jpPuzzle.setBackground(new java.awt.Color(51, 204, 0));
        jpPuzzle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpPuzzleRow1.setBackground(new java.awt.Color(51, 204, 0));

        jText12.setEditable(false);
        jText12.setBackground(new java.awt.Color(255, 255, 255));
        jText12.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText12.setText("A");
        jText12.setToolTipText("");
        jText12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText12.setVerifyInputWhenFocusTarget(false);

        jText11.setEditable(false);
        jText11.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText11.setText("A");
        jText11.setToolTipText("");
        jText11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText11.setVerifyInputWhenFocusTarget(false);

        jText10.setEditable(false);
        jText10.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText10.setText("A");
        jText10.setToolTipText("");
        jText10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText10.setVerifyInputWhenFocusTarget(false);

        jText9.setEditable(false);
        jText9.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText9.setText("A");
        jText9.setToolTipText("");
        jText9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText9.setVerifyInputWhenFocusTarget(false);

        jText8.setEditable(false);
        jText8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText8.setText("A");
        jText8.setToolTipText("");
        jText8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText8.setVerifyInputWhenFocusTarget(false);

        jText7.setEditable(false);
        jText7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText7.setText("A");
        jText7.setToolTipText("");
        jText7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText7.setVerifyInputWhenFocusTarget(false);

        jText6.setEditable(false);
        jText6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText6.setText("A");
        jText6.setToolTipText("");
        jText6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText6.setVerifyInputWhenFocusTarget(false);

        jText5.setEditable(false);
        jText5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText5.setText("A");
        jText5.setToolTipText("");
        jText5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText5.setVerifyInputWhenFocusTarget(false);

        jText4.setEditable(false);
        jText4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText4.setText("A");
        jText4.setToolTipText("");
        jText4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText4.setVerifyInputWhenFocusTarget(false);

        jText3.setEditable(false);
        jText3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText3.setText("A");
        jText3.setToolTipText("");
        jText3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText3.setVerifyInputWhenFocusTarget(false);

        jText2.setEditable(false);
        jText2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText2.setText("A");
        jText2.setToolTipText("");
        jText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText2.setVerifyInputWhenFocusTarget(false);

        jText1.setEditable(false);
        jText1.setBackground(new java.awt.Color(255, 255, 255));
        jText1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText1.setText("A");
        jText1.setToolTipText("");
        jText1.setAutoscrolls(false);
        jText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jpPuzzleRow1Layout = new javax.swing.GroupLayout(jpPuzzleRow1);
        jpPuzzleRow1.setLayout(jpPuzzleRow1Layout);
        jpPuzzleRow1Layout.setHorizontalGroup(
            jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpPuzzleRow1Layout.setVerticalGroup(
            jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPuzzleRow2.setBackground(new java.awt.Color(51, 204, 0));

        jText25.setEditable(false);
        jText25.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText25.setText("B");
        jText25.setToolTipText("");
        jText25.setAutoscrolls(false);
        jText25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText24.setEditable(false);
        jText24.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText24.setText("B");
        jText24.setToolTipText("");
        jText24.setAutoscrolls(false);
        jText24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText23.setEditable(false);
        jText23.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText23.setText("B");
        jText23.setToolTipText("");
        jText23.setAutoscrolls(false);
        jText23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText22.setEditable(false);
        jText22.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText22.setText("B");
        jText22.setToolTipText("");
        jText22.setAutoscrolls(false);
        jText22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText21.setEditable(false);
        jText21.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText21.setText("B");
        jText21.setToolTipText("");
        jText21.setAutoscrolls(false);
        jText21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText20.setEditable(false);
        jText20.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText20.setText("B");
        jText20.setToolTipText("");
        jText20.setAutoscrolls(false);
        jText20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText19.setEditable(false);
        jText19.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText19.setText("B");
        jText19.setToolTipText("");
        jText19.setAutoscrolls(false);
        jText19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText18.setEditable(false);
        jText18.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText18.setText("B");
        jText18.setToolTipText("");
        jText18.setAutoscrolls(false);
        jText18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText17.setEditable(false);
        jText17.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText17.setText("B");
        jText17.setToolTipText("");
        jText17.setAutoscrolls(false);
        jText17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText16.setEditable(false);
        jText16.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText16.setText("B");
        jText16.setToolTipText("");
        jText16.setAutoscrolls(false);
        jText16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText15.setEditable(false);
        jText15.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText15.setText("B");
        jText15.setToolTipText("");
        jText15.setAutoscrolls(false);
        jText15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText14.setEditable(false);
        jText14.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText14.setText("B");
        jText14.setToolTipText("");
        jText14.setAutoscrolls(false);
        jText14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText13.setEditable(false);
        jText13.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText13.setText("B");
        jText13.setToolTipText("");
        jText13.setAutoscrolls(false);
        jText13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText26.setEditable(false);
        jText26.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText26.setText("B");
        jText26.setToolTipText("");
        jText26.setAutoscrolls(false);
        jText26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow2Layout = new javax.swing.GroupLayout(jpPuzzleRow2);
        jpPuzzleRow2.setLayout(jpPuzzleRow2Layout);
        jpPuzzleRow2Layout.setHorizontalGroup(
            jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPuzzleRow2Layout.setVerticalGroup(
            jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPuzzleRow3.setBackground(new java.awt.Color(51, 204, 0));

        jText39.setEditable(false);
        jText39.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText39.setText("C");
        jText39.setToolTipText("");
        jText39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText38.setEditable(false);
        jText38.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText38.setText("C");
        jText38.setToolTipText("");
        jText38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText37.setEditable(false);
        jText37.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText37.setText("C");
        jText37.setToolTipText("");
        jText37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText36.setEditable(false);
        jText36.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText36.setText("C");
        jText36.setToolTipText("");
        jText36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText35.setEditable(false);
        jText35.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText35.setText("C");
        jText35.setToolTipText("");
        jText35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText34.setEditable(false);
        jText34.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText34.setText("C");
        jText34.setToolTipText("");
        jText34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText33.setEditable(false);
        jText33.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText33.setText("C");
        jText33.setToolTipText("");
        jText33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText32.setEditable(false);
        jText32.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText32.setText("C");
        jText32.setToolTipText("");
        jText32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText31.setEditable(false);
        jText31.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText31.setText("C");
        jText31.setToolTipText("");
        jText31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText30.setEditable(false);
        jText30.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText30.setText("C");
        jText30.setToolTipText("");
        jText30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText29.setEditable(false);
        jText29.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText29.setText("C");
        jText29.setToolTipText("");
        jText29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText28.setEditable(false);
        jText28.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText28.setText("C");
        jText28.setToolTipText("");
        jText28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText27.setEditable(false);
        jText27.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText27.setText("C");
        jText27.setToolTipText("");
        jText27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText40.setEditable(false);
        jText40.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText40.setText("C");
        jText40.setToolTipText("");
        jText40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow3Layout = new javax.swing.GroupLayout(jpPuzzleRow3);
        jpPuzzleRow3.setLayout(jpPuzzleRow3Layout);
        jpPuzzleRow3Layout.setHorizontalGroup(
            jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jText27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPuzzleRow3Layout.setVerticalGroup(
            jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPuzzleRow4.setBackground(new java.awt.Color(51, 204, 0));

        jText52.setEditable(false);
        jText52.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText52.setText("D");
        jText52.setToolTipText("");
        jText52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText51.setEditable(false);
        jText51.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText51.setText("D");
        jText51.setToolTipText("");
        jText51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText50.setEditable(false);
        jText50.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText50.setText("D");
        jText50.setToolTipText("");
        jText50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText49.setEditable(false);
        jText49.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText49.setText("D");
        jText49.setToolTipText("");
        jText49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText48.setEditable(false);
        jText48.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText48.setText("D");
        jText48.setToolTipText("");
        jText48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText47.setEditable(false);
        jText47.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText47.setText("D");
        jText47.setToolTipText("");
        jText47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText46.setEditable(false);
        jText46.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText46.setText("D");
        jText46.setToolTipText("");
        jText46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText45.setEditable(false);
        jText45.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText45.setText("D");
        jText45.setToolTipText("");
        jText45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText44.setEditable(false);
        jText44.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText44.setText("D");
        jText44.setToolTipText("");
        jText44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText43.setEditable(false);
        jText43.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText43.setText("D");
        jText43.setToolTipText("");
        jText43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText42.setEditable(false);
        jText42.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText42.setText("D");
        jText42.setToolTipText("");
        jText42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText41.setEditable(false);
        jText41.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText41.setText("D");
        jText41.setToolTipText("");
        jText41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow4Layout = new javax.swing.GroupLayout(jpPuzzleRow4);
        jpPuzzleRow4.setLayout(jpPuzzleRow4Layout);
        jpPuzzleRow4Layout.setHorizontalGroup(
            jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jText41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpPuzzleRow4Layout.setVerticalGroup(
            jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpPuzzleLayout = new javax.swing.GroupLayout(jpPuzzle);
        jpPuzzle.setLayout(jpPuzzleLayout);
        jpPuzzleLayout.setHorizontalGroup(
            jpPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPuzzleRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpPuzzleLayout.setVerticalGroup(
            jpPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPuzzleRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpBodyLayout.createSequentialGroup()
                                        .addComponent(jbGuess)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(190, 190, 190))
                                    .addGroup(jpBodyLayout.createSequentialGroup()
                                        .addComponent(jScrollPane6)
                                        .addGap(52, 52, 52))))
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlSpinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlPlayerTurnDisplay)
                                    .addComponent(jpPlayerTurnIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPlayerRank, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(jpPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGap(21, 21, 21))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPlayerRank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                        .addComponent(jlSpinValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                        .addComponent(jlPlayerTurnDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPlayerTurnIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitGameActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbQuitGameActionPerformed

    private void jbSpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSpinActionPerformed
        Tile spinValue = gameMenuControl.spin();
        this.jTWinValue.setText(GameMenuItems.LETTERWORTH.getText() + spinValue.getName());
        game.setGuessType(GuessType.CONSONANT);
        this.jTMessages.setText(GameMenuItems.GUESSCONSONANT.getText());
        setGuessControlVisibility(true);
    }//GEN-LAST:event_jbSpinActionPerformed

    private void jbGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuessActionPerformed
        String guess = jTGuess.getText().toUpperCase();
        if ("".equals(guess)){
            this.jTMessages.setText("Please enter a guess");
        } else {
            char guessedLetter = guess.charAt(0);
            switch(game.getGuessType()) {
                case CONSONANT:
                    consonantGuess(guessedLetter);
                    break;
                case VOWEL:
                    vowelGuess(guessedLetter);
                    break;
                case PUZZLE:
                    puzzleGuess(guess);
            }
        }
    }//GEN-LAST:event_jbGuessActionPerformed

    private void jbBuyVowelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuyVowelActionPerformed
        if(game.getCurrentPlayer().getPlayerRoundBank() >= 250){
            this.jTMessages.setText(GameMenuItems.GUESSVOWEL.getText());
            game.setGuessType(GuessType.VOWEL);
            setGuessControlVisibility(true);
        } else {
            this.jTMessages.setText(GameMenuItems.LOWBALANCE.getText());
        }
    }//GEN-LAST:event_jbBuyVowelActionPerformed
       
    private void consonantGuess(char guessedLetter){
        GuessAConsonant guessAConsonant = new GuessAConsonant();
        boolean validLetter = guessAConsonant.getInput(guessedLetter);
        if(validLetter){
            int correctLetters = game.getPuzzle().countLetters(guessedLetter);
            if(correctLetters > 0){
                game.getCurrentPlayer().setPlayerRoundBank(game.getSpinner().getCurrentSpinValue().getValue(),correctLetters);           
                this.jTMessages.setText("There are " + correctLetters + " " + guessedLetter + "'s. Your bank total is now: $" + game.getCurrentPlayer().getPlayerRoundBank());
                callInit();
            } else {
                game.changeCurrentPlayerTurn();
                this.jTMessages.setText(GameMenuItems.LETTERNOTFOUND.getText());
                callInit();
            }
        }
    }
    
    private void vowelGuess(char guessedLetter){
        GuessAVowel guessAVowel = new GuessAVowel();
        boolean validLetter = guessAVowel.getInput(guessedLetter);
        if(validLetter){
            int correctLetters = game.getPuzzle().countLetters(guessedLetter);
            if(correctLetters > 0){
                game.getCurrentPlayer().setPlayerRoundBank(-250,1);           
                this.jTMessages.setText("There are " + correctLetters + " " + guessedLetter + "'s. Your bank total is now: $" + game.getCurrentPlayer().getPlayerRoundBank());
                callInit();
            } else {
                game.changeCurrentPlayerTurn();
                this.jTMessages.setText(GameMenuItems.LETTERNOTFOUND.getText());
                callInit();
            }
        }
    }
    
    private void puzzleGuess(String guess){
        boolean result = gameMenuControl.solveThePuzzle(guess);
        if(result){
            this.jTMessages.setText(game.getCurrentPlayer().getPlayerName() 
                    + " wins! $" + game.getCurrentPlayer().getPlayerRoundBank()
                    + " in total winnings.");
            game.getPuzzle().makeWinningPuzzleVisible();
//            this.jTPuzzle.setText(game.displayPuzzle());
            displayTranslate(game.getPuzzle().getCurrentPuzzle());
            this.jTMessages.setText(this.jTMessages.getText() 
                + "Total turns played: "
                + game.getTotalNumberOfTurns() + "."
                + GameMenuItems.EXITMESSAGE.getText());
        } else {
            this.jTMessages.setText(GameMenuItems.WRONGGUESS.getText());
            game.changeCurrentPlayerTurn();
            callInit();
        }        
    }
    
    private void jbSolvePuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSolvePuzzleActionPerformed
        // TODO add your handling code here:
        game.setGuessType(GuessType.PUZZLE);
        this.jTMessages.setText(GameMenuItems.GUESSPUZZLE.getText());
        setGuessControlVisibility(true);
    }//GEN-LAST:event_jbSolvePuzzleActionPerformed

    private void setGuessControlVisibility(boolean visible){
        this.jbGuess.setEnabled(visible);
        this.jTGuess.setEnabled(visible);
        this.jTGuess.setText(null);
//        this.jTMessages.setText(null);
    }
            
    private void callInit(){
         try {
            this.initializeForm();
         } catch (RectangleOfFortuneException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
        
    private void displayTranslate(Letter[] puzzle) {
        //puzzle should be 52 characters in length
        this.jText1.setText(puzzle[0].showToWorld());
        this.jText2.setText(puzzle[1].showToWorld());
        this.jText3.setText(puzzle[2].showToWorld());
        this.jText4.setText(puzzle[3].showToWorld());
        this.jText5.setText(puzzle[4].showToWorld());
        this.jText6.setText(puzzle[5].showToWorld());
        this.jText7.setText(puzzle[6].showToWorld());
        this.jText8.setText(puzzle[7].showToWorld());
        this.jText9.setText(puzzle[8].showToWorld());
        this.jText10.setText(puzzle[9].showToWorld());
        this.jText11.setText(puzzle[10].showToWorld());
        this.jText12.setText(puzzle[11].showToWorld());
        this.jText13.setText(puzzle[12].showToWorld());
        this.jText14.setText(puzzle[13].showToWorld());
        this.jText15.setText(puzzle[14].showToWorld());
        this.jText16.setText(puzzle[15].showToWorld());
        this.jText17.setText(puzzle[16].showToWorld());
        this.jText18.setText(puzzle[17].showToWorld());
        this.jText19.setText(puzzle[18].showToWorld());
        this.jText20.setText(puzzle[19].showToWorld());
        this.jText21.setText(puzzle[20].showToWorld());
        this.jText22.setText(puzzle[21].showToWorld());
        this.jText23.setText(puzzle[22].showToWorld());
        this.jText24.setText(puzzle[23].showToWorld());
        this.jText25.setText(puzzle[24].showToWorld());
        this.jText26.setText(puzzle[25].showToWorld());
        this.jText27.setText(puzzle[26].showToWorld());
        this.jText28.setText(puzzle[27].showToWorld());
        this.jText29.setText(puzzle[28].showToWorld());
        this.jText30.setText(puzzle[29].showToWorld());
        this.jText31.setText(puzzle[30].showToWorld());
        this.jText32.setText(puzzle[31].showToWorld());
        this.jText33.setText(puzzle[32].showToWorld());
        this.jText34.setText(puzzle[33].showToWorld());
        this.jText35.setText(puzzle[34].showToWorld());
        this.jText36.setText(puzzle[35].showToWorld());
        this.jText37.setText(puzzle[36].showToWorld());
        this.jText38.setText(puzzle[37].showToWorld());
        this.jText39.setText(puzzle[38].showToWorld());
        this.jText40.setText(puzzle[39].showToWorld());
        this.jText41.setText(puzzle[40].showToWorld());
        this.jText42.setText(puzzle[41].showToWorld());
        this.jText43.setText(puzzle[42].showToWorld());
        this.jText44.setText(puzzle[43].showToWorld());
        this.jText45.setText(puzzle[44].showToWorld());
        this.jText46.setText(puzzle[45].showToWorld());
        this.jText47.setText(puzzle[46].showToWorld());
        this.jText48.setText(puzzle[47].showToWorld());
        this.jText49.setText(puzzle[48].showToWorld());
        this.jText50.setText(puzzle[49].showToWorld());
        this.jText51.setText(puzzle[50].showToWorld());
        this.jText52.setText(puzzle[51].showToWorld());
        
        
        
    }

    private void showBackground() {
        Letter[] puzzle=game.getPuzzle().getCurrentPuzzle();
        
        if (puzzle[0].getValue()==' ') {jText1.setBackground(Color.GRAY);}
        if (puzzle[1].getValue()==' ') {jText2.setBackground(Color.GRAY);}
        if (puzzle[2].getValue()==' ') {jText3.setBackground(Color.GRAY);}
        if (puzzle[3].getValue()==' ') {jText4.setBackground(Color.GRAY);}
        if (puzzle[4].getValue()==' ') {jText5.setBackground(Color.GRAY);}
        if (puzzle[5].getValue()==' ') {jText6.setBackground(Color.GRAY);}
        if (puzzle[6].getValue()==' ') {jText7.setBackground(Color.GRAY);}
        if (puzzle[7].getValue()==' ') {jText8.setBackground(Color.GRAY);}
        if (puzzle[8].getValue()==' ') {jText9.setBackground(Color.GRAY);}
        if (puzzle[9].getValue()==' ') {jText10.setBackground(Color.GRAY);}
        if (puzzle[10].getValue()==' ') {jText11.setBackground(Color.GRAY);}
        if (puzzle[11].getValue()==' ') {jText12.setBackground(Color.GRAY);}
        if (puzzle[12].getValue()==' ') {jText13.setBackground(Color.GRAY);}
        if (puzzle[13].getValue()==' ') {jText14.setBackground(Color.GRAY);}
        if (puzzle[14].getValue()==' ') {jText15.setBackground(Color.GRAY);}
        if (puzzle[15].getValue()==' ') {jText16.setBackground(Color.GRAY);}
        if (puzzle[16].getValue()==' ') {jText17.setBackground(Color.GRAY);}
        if (puzzle[17].getValue()==' ') {jText18.setBackground(Color.GRAY);}
        if (puzzle[18].getValue()==' ') {jText19.setBackground(Color.GRAY);}
        if (puzzle[19].getValue()==' ') {jText20.setBackground(Color.GRAY);}
        if (puzzle[20].getValue()==' ') {jText21.setBackground(Color.GRAY);}
        if (puzzle[21].getValue()==' ') {jText22.setBackground(Color.GRAY);}
        if (puzzle[22].getValue()==' ') {jText23.setBackground(Color.GRAY);}
        if (puzzle[23].getValue()==' ') {jText24.setBackground(Color.GRAY);}
        if (puzzle[24].getValue()==' ') {jText25.setBackground(Color.GRAY);}
        if (puzzle[25].getValue()==' ') {jText26.setBackground(Color.GRAY);}
        if (puzzle[26].getValue()==' ') {jText27.setBackground(Color.GRAY);}
        if (puzzle[27].getValue()==' ') {jText28.setBackground(Color.GRAY);}
        if (puzzle[28].getValue()==' ') {jText29.setBackground(Color.GRAY);}
        if (puzzle[29].getValue()==' ') {jText30.setBackground(Color.GRAY);}
        if (puzzle[30].getValue()==' ') {jText31.setBackground(Color.GRAY);}
        if (puzzle[31].getValue()==' ') {jText32.setBackground(Color.GRAY);}
        if (puzzle[32].getValue()==' ') {jText33.setBackground(Color.GRAY);}
        if (puzzle[33].getValue()==' ') {jText34.setBackground(Color.GRAY);}
        if (puzzle[34].getValue()==' ') {jText35.setBackground(Color.GRAY);}
        if (puzzle[35].getValue()==' ') {jText36.setBackground(Color.GRAY);}
        if (puzzle[36].getValue()==' ') {jText37.setBackground(Color.GRAY);}
        if (puzzle[37].getValue()==' ') {jText38.setBackground(Color.GRAY);}
        if (puzzle[38].getValue()==' ') {jText39.setBackground(Color.GRAY);}
        if (puzzle[39].getValue()==' ') {jText40.setBackground(Color.GRAY);}
        if (puzzle[40].getValue()==' ') {jText41.setBackground(Color.GRAY);}
        if (puzzle[41].getValue()==' ') {jText42.setBackground(Color.GRAY);}
        if (puzzle[42].getValue()==' ') {jText43.setBackground(Color.GRAY);}
        if (puzzle[43].getValue()==' ') {jText44.setBackground(Color.GRAY);}
        if (puzzle[44].getValue()==' ') {jText45.setBackground(Color.GRAY);}
        if (puzzle[45].getValue()==' ') {jText46.setBackground(Color.GRAY);}
        if (puzzle[46].getValue()==' ') {jText47.setBackground(Color.GRAY);}
        if (puzzle[47].getValue()==' ') {jText48.setBackground(Color.GRAY);}
        if (puzzle[48].getValue()==' ') {jText49.setBackground(Color.GRAY);}
        if (puzzle[49].getValue()==' ') {jText50.setBackground(Color.GRAY);}
        if (puzzle[50].getValue()==' ') {jText51.setBackground(Color.GRAY);}
        if (puzzle[51].getValue()==' ') {jText52.setBackground(Color.GRAY);}

    }
        
    
    
//    private void setGuessVowelControlVisibility(boolean visible){
//        this.jbGuessVowel.setEnabled(visible);
//        this.jTGuessVowel.setEnabled(visible);
//        this.jTGuessVowel.setText(null);
//    }
    
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jPlayerRankText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTGuess;
    private javax.swing.JTextArea jTMessages;
    private javax.swing.JTextArea jTWinValue;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText10;
    private javax.swing.JTextField jText11;
    private javax.swing.JTextField jText12;
    private javax.swing.JTextField jText13;
    private javax.swing.JTextField jText14;
    private javax.swing.JTextField jText15;
    private javax.swing.JTextField jText16;
    private javax.swing.JTextField jText17;
    private javax.swing.JTextField jText18;
    private javax.swing.JTextField jText19;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText20;
    private javax.swing.JTextField jText21;
    private javax.swing.JTextField jText22;
    private javax.swing.JTextField jText23;
    private javax.swing.JTextField jText24;
    private javax.swing.JTextField jText25;
    private javax.swing.JTextField jText26;
    private javax.swing.JTextField jText27;
    private javax.swing.JTextField jText28;
    private javax.swing.JTextField jText29;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jText30;
    private javax.swing.JTextField jText31;
    private javax.swing.JTextField jText32;
    private javax.swing.JTextField jText33;
    private javax.swing.JTextField jText34;
    private javax.swing.JTextField jText35;
    private javax.swing.JTextField jText36;
    private javax.swing.JTextField jText37;
    private javax.swing.JTextField jText38;
    private javax.swing.JTextField jText39;
    private javax.swing.JTextField jText4;
    private javax.swing.JTextField jText40;
    private javax.swing.JTextField jText41;
    private javax.swing.JTextField jText42;
    private javax.swing.JTextField jText43;
    private javax.swing.JTextField jText44;
    private javax.swing.JTextField jText45;
    private javax.swing.JTextField jText46;
    private javax.swing.JTextField jText47;
    private javax.swing.JTextField jText48;
    private javax.swing.JTextField jText49;
    private javax.swing.JTextField jText5;
    private javax.swing.JTextField jText50;
    private javax.swing.JTextField jText51;
    private javax.swing.JTextField jText52;
    private javax.swing.JTextField jText6;
    private javax.swing.JTextField jText7;
    private javax.swing.JTextField jText8;
    private javax.swing.JTextField jText9;
    private javax.swing.JButton jbBuyVowel;
    private javax.swing.JButton jbGuess;
    private javax.swing.JButton jbQuitGame;
    private javax.swing.JButton jbSolvePuzzle;
    private javax.swing.JButton jbSpin;
    private javax.swing.JLabel jlPlayerRank;
    private javax.swing.JLabel jlPlayerTurn;
    private javax.swing.JLabel jlPlayerTurnDisplay;
    private javax.swing.JLabel jlSpinValue;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpPlayerTurnIndicator;
    private javax.swing.JPanel jpPuzzle;
    private javax.swing.JPanel jpPuzzleRow1;
    private javax.swing.JPanel jpPuzzleRow2;
    private javax.swing.JPanel jpPuzzleRow3;
    private javax.swing.JPanel jpPuzzleRow4;
    // End of variables declaration//GEN-END:variables
}
