/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package BYUI.CIT260.RectangleOfFortune.frames;

import BYUI.CIT260.RectangleOfFortune.Enums.HelpMenuItems;
import BYUI.CIT260.RectangleOfFortune.menu.controls.MainMenuControl;


/**
 *
 * @author Crossley Family
 */
public class HelpMenuFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public HelpMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpMenuItems = new javax.swing.JPanel();
        jbOnePlayer = new javax.swing.JButton();
        jbTwoPlayer = new javax.swing.JButton();
        jbThreePlayer = new javax.swing.JButton();
        jbHelpMenu = new javax.swing.JButton();
        jbExitGame = new javax.swing.JButton();
        jbExitGame1 = new javax.swing.JButton();
        jbExitGame2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHelpIntro = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help Menu - Rectangle of Fortune");

        jpBody.setBackground(new java.awt.Color(204, 255, 255));
        jpBody.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));

        jpTitle.setBackground(new java.awt.Color(204, 255, 255));

        jlTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jlTitle.setText("Rectangle of Fortune");
        jlTitle.setToolTipText("");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMenuItems.setBackground(new java.awt.Color(204, 255, 255));
        jpMenuItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbOnePlayer.setText("Rectangle of Fortune Game");
        jbOnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowGameIntroActionPerformed(evt);
            }
        });

        jbTwoPlayer.setText("The Rectangle");
        jbTwoPlayer.setToolTipText("");
        jbTwoPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowRectangleActionPerformed(evt);
            }
        });

        jbThreePlayer.setText("Computer Player");
        jbThreePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComputerPlayerHelpActionPerformed(evt);
            }
        });

        jbHelpMenu.setText("Taking Your Turn");
        jbHelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTurnHelpInfoActionPerformed(evt);
            }
        });

        jbExitGame.setText("Puzzle");
        jbExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPuzzleHelpInfoActionPerformed(evt);
            }
        });

        jbExitGame1.setText("Bank");
        jbExitGame1.setToolTipText("");
        jbExitGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBankHelpInfoActionPerformed(evt);
            }
        });

        jbExitGame2.setText("Exit");
        jbExitGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbHelpMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbThreePlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbTwoPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMenuItemsLayout.createSequentialGroup()
                        .addComponent(jbOnePlayer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbExitGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExitGame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExitGame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbOnePlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTwoPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbThreePlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHelpMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExitGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExitGame1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExitGame2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTHelpIntro.setEditable(false);
        jTHelpIntro.setColumns(20);
        jTHelpIntro.setLineWrap(true);
        jTHelpIntro.setRows(5);
        jTHelpIntro.setText("The objective of the game is to be the first player to correctly guess the puzzle word or phrase. Each player takes turns spinning for a value of correctly guessedconsonants, then guesses a single consonant. Guessing an incorrect consonant or a consonant already guessed in the round is the end of the turn. Play resumes with the next player spinning either guessing a consonant, buying remaining vowels, or guessing the puzzle.Players may buy a vowel if they have at least $250 in their bank.");
        jTHelpIntro.setWrapStyleWord(true);
        jTHelpIntro.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jTHelpIntro);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPuzzleHelpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPuzzleHelpInfoActionPerformed
        // TODO add your hdling code here:
        jTHelpIntro.setText(HelpMenuItems.PUZZLE.getHelpText());
    }//GEN-LAST:event_jbPuzzleHelpInfoActionPerformed

    private void jbShowGameIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowGameIntroActionPerformed
        jTHelpIntro.setText(HelpMenuItems.GAME.getHelpText());
    }//GEN-LAST:event_jbShowGameIntroActionPerformed

    private void jbShowRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowRectangleActionPerformed
        jTHelpIntro.setText(HelpMenuItems.RECTANGLE.getHelpText());
    }//GEN-LAST:event_jbShowRectangleActionPerformed

    private void jbComputerPlayerHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComputerPlayerHelpActionPerformed
        jTHelpIntro.setText(HelpMenuItems.COMPUTER.getHelpText());
    }//GEN-LAST:event_jbComputerPlayerHelpActionPerformed
    
    private void jbTurnHelpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTurnHelpInfoActionPerformed
        jTHelpIntro.setText(HelpMenuItems.TURN.getHelpText());
    }//GEN-LAST:event_jbTurnHelpInfoActionPerformed

    private void jbBankHelpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBankHelpInfoActionPerformed
        jTHelpIntro.setText(HelpMenuItems.BANK.getHelpText());
    }//GEN-LAST:event_jbBankHelpInfoActionPerformed

    private void jbExitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitHelpActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbExitHelpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTHelpIntro;
    private javax.swing.JButton jbExitGame;
    private javax.swing.JButton jbExitGame1;
    private javax.swing.JButton jbExitGame2;
    private javax.swing.JButton jbHelpMenu;
    private javax.swing.JButton jbOnePlayer;
    private javax.swing.JButton jbThreePlayer;
    private javax.swing.JButton jbTwoPlayer;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle;
    // End of variables declaration//GEN-END:variables
}
