/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package BYUI.CIT260.RectangleOfFortune.frames;

import BYUI.CIT260.RectangleOfFortune.models.Letter;
import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author Crossley Family
 */
public class PuzzleDisplayTest extends javax.swing.JPanel {

    /**
     * Creates new form PuzzleDisplayTest
     */
    public PuzzleDisplayTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPuzzle = new javax.swing.JPanel();
        jpPuzzleRow1 = new javax.swing.JPanel();
        jText12 = new javax.swing.JTextField();
        jText11 = new javax.swing.JTextField();
        jText10 = new javax.swing.JTextField();
        jText9 = new javax.swing.JTextField();
        jText8 = new javax.swing.JTextField();
        jText7 = new javax.swing.JTextField();
        jText6 = new javax.swing.JTextField();
        jText5 = new javax.swing.JTextField();
        jText4 = new javax.swing.JTextField();
        jText3 = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jText1 = new javax.swing.JTextField();
        jpPuzzleRow2 = new javax.swing.JPanel();
        jText25 = new javax.swing.JTextField();
        jText24 = new javax.swing.JTextField();
        jText23 = new javax.swing.JTextField();
        jText22 = new javax.swing.JTextField();
        jText21 = new javax.swing.JTextField();
        jText20 = new javax.swing.JTextField();
        jText19 = new javax.swing.JTextField();
        jText18 = new javax.swing.JTextField();
        jText17 = new javax.swing.JTextField();
        jText16 = new javax.swing.JTextField();
        jText15 = new javax.swing.JTextField();
        jText14 = new javax.swing.JTextField();
        jText13 = new javax.swing.JTextField();
        jText26 = new javax.swing.JTextField();
        jpPuzzleRow3 = new javax.swing.JPanel();
        jText39 = new javax.swing.JTextField();
        jText38 = new javax.swing.JTextField();
        jText37 = new javax.swing.JTextField();
        jText36 = new javax.swing.JTextField();
        jText35 = new javax.swing.JTextField();
        jText34 = new javax.swing.JTextField();
        jText33 = new javax.swing.JTextField();
        jText32 = new javax.swing.JTextField();
        jText31 = new javax.swing.JTextField();
        jText30 = new javax.swing.JTextField();
        jText29 = new javax.swing.JTextField();
        jText28 = new javax.swing.JTextField();
        jText27 = new javax.swing.JTextField();
        jText40 = new javax.swing.JTextField();
        jpPuzzleRow4 = new javax.swing.JPanel();
        jText52 = new javax.swing.JTextField();
        jText51 = new javax.swing.JTextField();
        jText50 = new javax.swing.JTextField();
        jText49 = new javax.swing.JTextField();
        jText48 = new javax.swing.JTextField();
        jText47 = new javax.swing.JTextField();
        jText46 = new javax.swing.JTextField();
        jText45 = new javax.swing.JTextField();
        jText44 = new javax.swing.JTextField();
        jText43 = new javax.swing.JTextField();
        jText42 = new javax.swing.JTextField();
        jText41 = new javax.swing.JTextField();
        jbTest = new javax.swing.JButton();

        jpPuzzle.setBackground(new java.awt.Color(51, 204, 0));
        jpPuzzle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpPuzzleRow1.setBackground(new java.awt.Color(51, 204, 0));

        jText12.setEditable(false);
        jText12.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText12.setText("A");
        jText12.setToolTipText("");
        jText12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText12.setVerifyInputWhenFocusTarget(false);

        jText11.setEditable(false);
        jText11.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText11.setText("A");
        jText11.setToolTipText("");
        jText11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText11.setVerifyInputWhenFocusTarget(false);

        jText10.setEditable(false);
        jText10.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText10.setText("A");
        jText10.setToolTipText("");
        jText10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText10.setVerifyInputWhenFocusTarget(false);

        jText9.setEditable(false);
        jText9.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText9.setText("A");
        jText9.setToolTipText("");
        jText9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText9.setVerifyInputWhenFocusTarget(false);

        jText8.setEditable(false);
        jText8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText8.setText("A");
        jText8.setToolTipText("");
        jText8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText8.setVerifyInputWhenFocusTarget(false);

        jText7.setEditable(false);
        jText7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText7.setText("A");
        jText7.setToolTipText("");
        jText7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText7.setVerifyInputWhenFocusTarget(false);

        jText6.setEditable(false);
        jText6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText6.setText("A");
        jText6.setToolTipText("");
        jText6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText6.setVerifyInputWhenFocusTarget(false);

        jText5.setEditable(false);
        jText5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText5.setText("A");
        jText5.setToolTipText("");
        jText5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText5.setVerifyInputWhenFocusTarget(false);

        jText4.setEditable(false);
        jText4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText4.setText("A");
        jText4.setToolTipText("");
        jText4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText4.setVerifyInputWhenFocusTarget(false);

        jText3.setEditable(false);
        jText3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText3.setText("A");
        jText3.setToolTipText("");
        jText3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText3.setVerifyInputWhenFocusTarget(false);

        jText2.setEditable(false);
        jText2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText2.setText("A");
        jText2.setToolTipText("");
        jText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText2.setVerifyInputWhenFocusTarget(false);

        jText1.setEditable(false);
        jText1.setBackground(new java.awt.Color(255, 255, 255));
        jText1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText1.setText("A");
        jText1.setToolTipText("");
        jText1.setAutoscrolls(false);
        jText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jText1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jpPuzzleRow1Layout = new javax.swing.GroupLayout(jpPuzzleRow1);
        jpPuzzleRow1.setLayout(jpPuzzleRow1Layout);
        jpPuzzleRow1Layout.setHorizontalGroup(
            jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpPuzzleRow1Layout.setVerticalGroup(
            jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jText12.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText11.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText10.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText9.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText8.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText7.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText6.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText5.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText4.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText3.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText2.getAccessibleContext().setAccessibleName("PuzzleLetter");
        jText1.getAccessibleContext().setAccessibleName("PuzzleLetter");

        jpPuzzleRow2.setBackground(new java.awt.Color(51, 204, 0));

        jText25.setEditable(false);
        jText25.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText25.setText("B");
        jText25.setToolTipText("");
        jText25.setAutoscrolls(false);
        jText25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText24.setEditable(false);
        jText24.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText24.setText("B");
        jText24.setToolTipText("");
        jText24.setAutoscrolls(false);
        jText24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText23.setEditable(false);
        jText23.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText23.setText("B");
        jText23.setToolTipText("");
        jText23.setAutoscrolls(false);
        jText23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText22.setEditable(false);
        jText22.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText22.setText("B");
        jText22.setToolTipText("");
        jText22.setAutoscrolls(false);
        jText22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText21.setEditable(false);
        jText21.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText21.setText("B");
        jText21.setToolTipText("");
        jText21.setAutoscrolls(false);
        jText21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText20.setEditable(false);
        jText20.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText20.setText("B");
        jText20.setToolTipText("");
        jText20.setAutoscrolls(false);
        jText20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText19.setEditable(false);
        jText19.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText19.setText("B");
        jText19.setToolTipText("");
        jText19.setAutoscrolls(false);
        jText19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText18.setEditable(false);
        jText18.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText18.setText("B");
        jText18.setToolTipText("");
        jText18.setAutoscrolls(false);
        jText18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText17.setEditable(false);
        jText17.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText17.setText("B");
        jText17.setToolTipText("");
        jText17.setAutoscrolls(false);
        jText17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText16.setEditable(false);
        jText16.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText16.setText("B");
        jText16.setToolTipText("");
        jText16.setAutoscrolls(false);
        jText16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText15.setEditable(false);
        jText15.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText15.setText("B");
        jText15.setToolTipText("");
        jText15.setAutoscrolls(false);
        jText15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText14.setEditable(false);
        jText14.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText14.setText("B");
        jText14.setToolTipText("");
        jText14.setAutoscrolls(false);
        jText14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText13.setEditable(false);
        jText13.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText13.setText("B");
        jText13.setToolTipText("");
        jText13.setAutoscrolls(false);
        jText13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText26.setEditable(false);
        jText26.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText26.setText("B");
        jText26.setToolTipText("");
        jText26.setAutoscrolls(false);
        jText26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow2Layout = new javax.swing.GroupLayout(jpPuzzleRow2);
        jpPuzzleRow2.setLayout(jpPuzzleRow2Layout);
        jpPuzzleRow2Layout.setHorizontalGroup(
            jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPuzzleRow2Layout.setVerticalGroup(
            jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPuzzleRow3.setBackground(new java.awt.Color(51, 204, 0));

        jText39.setEditable(false);
        jText39.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText39.setText("C");
        jText39.setToolTipText("");
        jText39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText38.setEditable(false);
        jText38.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText38.setText("C");
        jText38.setToolTipText("");
        jText38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText37.setEditable(false);
        jText37.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText37.setText("C");
        jText37.setToolTipText("");
        jText37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText36.setEditable(false);
        jText36.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText36.setText("C");
        jText36.setToolTipText("");
        jText36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText35.setEditable(false);
        jText35.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText35.setText("C");
        jText35.setToolTipText("");
        jText35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText34.setEditable(false);
        jText34.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText34.setText("C");
        jText34.setToolTipText("");
        jText34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText33.setEditable(false);
        jText33.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText33.setText("C");
        jText33.setToolTipText("");
        jText33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText32.setEditable(false);
        jText32.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText32.setText("C");
        jText32.setToolTipText("");
        jText32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText31.setEditable(false);
        jText31.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText31.setText("C");
        jText31.setToolTipText("");
        jText31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText30.setEditable(false);
        jText30.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText30.setText("C");
        jText30.setToolTipText("");
        jText30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText29.setEditable(false);
        jText29.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText29.setText("C");
        jText29.setToolTipText("");
        jText29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText28.setEditable(false);
        jText28.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText28.setText("C");
        jText28.setToolTipText("");
        jText28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText27.setEditable(false);
        jText27.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText27.setText("C");
        jText27.setToolTipText("");
        jText27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText40.setEditable(false);
        jText40.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText40.setText("C");
        jText40.setToolTipText("");
        jText40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow3Layout = new javax.swing.GroupLayout(jpPuzzleRow3);
        jpPuzzleRow3.setLayout(jpPuzzleRow3Layout);
        jpPuzzleRow3Layout.setHorizontalGroup(
            jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jText27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPuzzleRow3Layout.setVerticalGroup(
            jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPuzzleRow4.setBackground(new java.awt.Color(51, 204, 0));

        jText52.setEditable(false);
        jText52.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText52.setText("D");
        jText52.setToolTipText("");
        jText52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText51.setEditable(false);
        jText51.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText51.setText("D");
        jText51.setToolTipText("");
        jText51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText50.setEditable(false);
        jText50.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText50.setText("D");
        jText50.setToolTipText("");
        jText50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText49.setEditable(false);
        jText49.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText49.setText("D");
        jText49.setToolTipText("");
        jText49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText48.setEditable(false);
        jText48.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText48.setText("D");
        jText48.setToolTipText("");
        jText48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText47.setEditable(false);
        jText47.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText47.setText("D");
        jText47.setToolTipText("");
        jText47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText46.setEditable(false);
        jText46.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText46.setText("D");
        jText46.setToolTipText("");
        jText46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText45.setEditable(false);
        jText45.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText45.setText("D");
        jText45.setToolTipText("");
        jText45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText44.setEditable(false);
        jText44.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText44.setText("D");
        jText44.setToolTipText("");
        jText44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText43.setEditable(false);
        jText43.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText43.setText("D");
        jText43.setToolTipText("");
        jText43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText42.setEditable(false);
        jText42.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText42.setText("D");
        jText42.setToolTipText("");
        jText42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText41.setEditable(false);
        jText41.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jText41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText41.setText("D");
        jText41.setToolTipText("");
        jText41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPuzzleRow4Layout = new javax.swing.GroupLayout(jpPuzzleRow4);
        jpPuzzleRow4.setLayout(jpPuzzleRow4Layout);
        jpPuzzleRow4Layout.setHorizontalGroup(
            jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jText41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpPuzzleRow4Layout.setVerticalGroup(
            jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleRow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jText41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jText52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpPuzzleLayout = new javax.swing.GroupLayout(jpPuzzle);
        jpPuzzle.setLayout(jpPuzzleLayout);
        jpPuzzleLayout.setHorizontalGroup(
            jpPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPuzzleRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPuzzleRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpPuzzleLayout.setVerticalGroup(
            jpPuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPuzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPuzzleRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPuzzleRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbTest.setText("test");
        jbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTest)
                .addGap(385, 385, 385))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPuzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTest)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
        // TODO add your handling code here:
        String puzzleText="Hello World";
        int nextWordStart=16;
        int currentWordLength=5;
        int currentWordChar=1;
        int currentPuzzleChar=1;
        
        Letter[] puzzle= new Letter[52];
        for(int i=1;i<=52;i++){
            Letter letter;
            if (nextWordStart>=i && i<=currentWordLength){
                letter = new Letter(puzzleText.charAt(currentWordChar));
                currentWordChar++;
            } else{
                letter = new Letter(' ');
            }
            puzzle[i]=letter;
            
        }
        Component[] compArr = jpPuzzle.getComponents();
        for (Component comp : compArr) {
            if (comp instanceof JTextField) {
                System.out.println(((JTextField)comp).getName());
                System.out.println(((JTextField)comp).getText());
            }
        }       
    }//GEN-LAST:event_jbTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText10;
    private javax.swing.JTextField jText11;
    private javax.swing.JTextField jText12;
    private javax.swing.JTextField jText13;
    private javax.swing.JTextField jText14;
    private javax.swing.JTextField jText15;
    private javax.swing.JTextField jText16;
    private javax.swing.JTextField jText17;
    private javax.swing.JTextField jText18;
    private javax.swing.JTextField jText19;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText20;
    private javax.swing.JTextField jText21;
    private javax.swing.JTextField jText22;
    private javax.swing.JTextField jText23;
    private javax.swing.JTextField jText24;
    private javax.swing.JTextField jText25;
    private javax.swing.JTextField jText26;
    private javax.swing.JTextField jText27;
    private javax.swing.JTextField jText28;
    private javax.swing.JTextField jText29;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jText30;
    private javax.swing.JTextField jText31;
    private javax.swing.JTextField jText32;
    private javax.swing.JTextField jText33;
    private javax.swing.JTextField jText34;
    private javax.swing.JTextField jText35;
    private javax.swing.JTextField jText36;
    private javax.swing.JTextField jText37;
    private javax.swing.JTextField jText38;
    private javax.swing.JTextField jText39;
    private javax.swing.JTextField jText4;
    private javax.swing.JTextField jText40;
    private javax.swing.JTextField jText41;
    private javax.swing.JTextField jText42;
    private javax.swing.JTextField jText43;
    private javax.swing.JTextField jText44;
    private javax.swing.JTextField jText45;
    private javax.swing.JTextField jText46;
    private javax.swing.JTextField jText47;
    private javax.swing.JTextField jText48;
    private javax.swing.JTextField jText49;
    private javax.swing.JTextField jText5;
    private javax.swing.JTextField jText50;
    private javax.swing.JTextField jText51;
    private javax.swing.JTextField jText52;
    private javax.swing.JTextField jText6;
    private javax.swing.JTextField jText7;
    private javax.swing.JTextField jText8;
    private javax.swing.JTextField jText9;
    private javax.swing.JButton jbTest;
    private javax.swing.JPanel jpPuzzle;
    private javax.swing.JPanel jpPuzzleRow1;
    private javax.swing.JPanel jpPuzzleRow2;
    private javax.swing.JPanel jpPuzzleRow3;
    private javax.swing.JPanel jpPuzzleRow4;
    // End of variables declaration//GEN-END:variables
}
